# Generated by Django 5.2.17 on 2026-09-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # AOI 表独立 schema；仅支持 PostgreSQL（计划 §2 决策 3）
        migrations.RunSQL(
            "CREATE SCHEMA IF NOT EXISTS aoi_audit;",
            reverse_sql="DROP SCHEMA IF EXISTS aoi_audit CASCADE;",
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor_id', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(blank=True, max_length=64, null=True)),
                ('object_type', models.CharField(blank=True, max_length=32, null=True)),
                ('object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"aoi_audit"."audit_log"',
            },
        ),
    ]
