# Generated by Django 5.2.17 on 2026-09-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # AOI 表独立 schema；仅支持 PostgreSQL（计划 §2 决策 3）
        migrations.RunSQL(
            "CREATE SCHEMA IF NOT EXISTS aoi_training;",
            reverse_sql="DROP SCHEMA IF EXISTS aoi_training CASCADE;",
        ),
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('framework', models.CharField(max_length=16)),
                ('task_type', models.CharField(default='ObjectDetection', max_length=32)),
                ('weights_key', models.TextField(blank=True, null=True)),
                ('params_schema', models.JSONField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': '"aoi_training"."base_model"',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=64, unique=True)),
                ('framework', models.CharField(blank=True, max_length=16, null=True)),
                ('dataset_version', models.CharField(blank=True, max_length=16, null=True)),
                ('task_type', models.CharField(default='ObjectDetection', max_length=32)),
                ('base_model', models.CharField(blank=True, max_length=64, null=True)),
                ('weights_key', models.TextField(blank=True, null=True)),
                ('class_names', models.JSONField(default=list)),
                ('cover_classes', models.JSONField(default=list)),
                ('precision', models.CharField(default='fp32', max_length=8)),
                ('input_shape', models.JSONField(blank=True, null=True)),
                ('tensor_names', models.JSONField(blank=True, null=True)),
                ('eval_metrics', models.JSONField(blank=True, null=True)),
                ('gate_status', models.CharField(default='pending', max_length=16)),
                ('llm_review', models.JSONField(blank=True, null=True)),
                ('lifecycle', models.CharField(default='candidate', max_length=16)),
                ('config_snapshot', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': '"aoi_training"."model"',
            },
        ),
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('framework', models.CharField(max_length=16)),
                ('task_type', models.CharField(default='ObjectDetection', max_length=32)),
                ('base_model', models.CharField(blank=True, max_length=64, null=True)),
                ('params', models.JSONField(blank=True, null=True)),
                ('class_subset', models.JSONField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': '"aoi_training"."preset"',
            },
        ),
        migrations.CreateModel(
            name='TrainJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataset_version', models.CharField(max_length=16)),
                ('framework', models.CharField(max_length=16)),
                ('task_type', models.CharField(default='ObjectDetection', max_length=32)),
                ('preset', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('succeeded', 'succeeded'), ('failed', 'failed'), ('canceled', 'canceled')], default='queued', max_length=16)),
                ('celery_task_id', models.CharField(blank=True, max_length=128, null=True)),
                ('metrics', models.JSONField(blank=True, null=True)),
                ('artifact_path', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"aoi_training"."train_job"',
            },
        ),
    ]
