# Generated by Django 5.2.17 on 2026-09-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi_training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPublish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_ref', models.CharField(max_length=64, unique=True)),
                ('registry', models.CharField(max_length=128)),
                ('image', models.CharField(max_length=256)),
                ('tag', models.CharField(max_length=128)),
                ('digest', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('building', 'building'), ('pushing', 'pushing'), ('published', 'published'), ('failed', 'failed')], default='queued', max_length=16)),
                ('attempts', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('published_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"aoi_training"."model_publish"',
            },
        ),
    ]
