# Generated by Django 5.2.17 on 2026-09-10 03:01
# 手工补充（P1）：0002 用 CreateModel(unique=True) 建表时，Postgres 生成的是内联 UNIQUE 约束
# `model_publish_model_ref_key`；由于 db_table 是 schema-qualified（"aoi_training"."model_publish"），
# Django 的 AlterField 内省不到该约束，不会自动删除 —— 必须显式 DROP，否则 (model_ref, tag)
# 的新唯一性被旧约束压制（fp16 tag 依然发不出去）。

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi_training', '0002_model_publish'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE "aoi_training"."model_publish" DROP CONSTRAINT IF EXISTS "model_publish_model_ref_key";',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='modelpublish',
            name='model_ref',
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name='modelpublish',
            constraint=models.UniqueConstraint(fields=('model_ref', 'tag'), name='uniq_model_publish_ref_tag'),
        ),
    ]
