# Generated by Django 5.2.17 on 2026-09-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi_training', '0003_p1_publish_unique_ref_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpublish',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelpublish',
            name='deleted_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
