# Generated by Django 5.2.17 on 2026-09-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # AOI 表独立 schema；仅支持 PostgreSQL（计划 §2 决策 3）
        migrations.RunSQL(
            "CREATE SCHEMA IF NOT EXISTS aoi_review;",
            reverse_sql="DROP SCHEMA IF EXISTS aoi_review CASCADE;",
        ),
        migrations.CreateModel(
            name='FeedbackSuggestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('workitem_id', models.BigIntegerField(blank=True, null=True)),
                ('image_id', models.IntegerField(blank=True, null=True)),
                ('rule_code', models.CharField(blank=True, max_length=8, null=True)),
                ('suggestion', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='suggested', max_length=16)),
                ('confirmed_by', models.IntegerField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"aoi_review"."feedback_suggestion"',
            },
        ),
        migrations.CreateModel(
            name='FinalFact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fact_id', models.BigIntegerField(blank=True, null=True)),
                ('verdict', models.CharField(blank=True, max_length=32, null=True)),
                ('class_id', models.IntegerField(blank=True, null=True)),
                ('boxes', models.JSONField(blank=True, null=True)),
                ('decided_by', models.IntegerField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"aoi_review"."final_fact"',
            },
        ),
        migrations.CreateModel(
            name='ReviewWorkitem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fact_id', models.BigIntegerField()),
                ('route', models.CharField(max_length=16)),
                ('recheck_result', models.JSONField(blank=True, null=True)),
                ('hv_key', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('assignee_id', models.IntegerField(blank=True, null=True)),
                ('final_verdict', models.CharField(blank=True, max_length=32, null=True)),
                ('final_reason', models.CharField(blank=True, max_length=16, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"aoi_review"."review_workitem"',
            },
        ),
        migrations.CreateModel(
            name='BadImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('station_code', models.CharField(max_length=32)),
                ('station_name', models.CharField(blank=True, max_length=64, null=True)),
                ('seq', models.BigIntegerField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=16, null=True)),
                ('image_key', models.TextField(blank=True, null=True)),
                ('instance_code', models.CharField(blank=True, max_length=32, null=True)),
                ('handled', models.BooleanField(default=False)),
                ('handled_by', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"aoi_review"."bad_image"',
                'constraints': [models.UniqueConstraint(fields=('station_code', 'seq'), name='uniq_bad_station_seq')],
            },
        ),
        migrations.CreateModel(
            name='InspectionFact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_id', models.IntegerField(blank=True, null=True)),
                ('station_code', models.CharField(max_length=32)),
                ('station_name', models.CharField(blank=True, max_length=64, null=True)),
                ('seq', models.BigIntegerField(blank=True, null=True)),
                ('channel_id', models.IntegerField(blank=True, null=True)),
                ('template_version', models.IntegerField(blank=True, null=True)),
                ('result_json', models.JSONField(default=dict)),
                ('verdict', models.CharField(blank=True, max_length=16, null=True)),
                ('instance_code', models.CharField(blank=True, max_length=32, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='initial', max_length=16)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"aoi_review"."inspection_fact"',
                'constraints': [models.UniqueConstraint(fields=('station_code', 'seq'), name='uniq_fact_station_seq')],
            },
        ),
    ]
