# Generated by Django 5.2.17 on 2026-09-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi_review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalfact',
            name='action',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='finalfact',
            name='annotation_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalfact',
            name='dataset_version_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalfact',
            name='image_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalfact',
            name='ls_task_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalfact',
            name='source',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='finalfact',
            name='workitem_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewworkitem',
            name='bucket',
            field=models.CharField(blank=True, choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='reviewworkitem',
            name='bucket_reason',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewworkitem',
            name='dataset_version_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewworkitem',
            name='forced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewworkitem',
            name='image_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewworkitem',
            name='ls_prediction_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewworkitem',
            name='ls_task_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewworkitem',
            name='model_ref',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='reviewworkitem',
            name='source',
            field=models.CharField(choices=[('ingest', 'ingest'), ('prelabel', 'prelabel')], default='ingest', max_length=16),
        ),
        migrations.AddField(
            model_name='reviewworkitem',
            name='verdict',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='reviewworkitem',
            name='fact_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
