# Generated by Django 5.2.17 on 2026-09-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoi_review', '0002_review_workitem_bucket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewworkitem',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='finalfact',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewworkitem',
            name='route',
            field=models.CharField(choices=[('vlm', 'vlm'), ('manual', 'manual')], max_length=16),
        ),
        migrations.AlterField(
            model_name='reviewworkitem',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('finalized', 'finalized'), ('failed', 'failed')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='reviewworkitem',
            name='verdict',
            field=models.CharField(blank=True, choices=[('auto_pass', 'auto_pass'), ('recheck', 'recheck'), ('manual', 'manual')], max_length=16, null=True),
        ),
        migrations.AddIndex(
            model_name='reviewworkitem',
            index=models.Index(fields=['source', 'status'], name='idx_workitem_source_status'),
        ),
        migrations.AddIndex(
            model_name='reviewworkitem',
            index=models.Index(fields=['dataset_version_id', 'bucket', 'status'], name='idx_workitem_ds_bucket_status'),
        ),
        migrations.AddIndex(
            model_name='reviewworkitem',
            index=models.Index(fields=['fact_id', 'source'], name='idx_workitem_fact_source'),
        ),
        migrations.AddConstraint(
            model_name='finalfact',
            constraint=models.UniqueConstraint(fields=('workitem_id',), name='uniq_final_fact_workitem'),
        ),
    ]
