# Generated by Django 5.2.17 on 2026-09-14 03:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # AOI 表独立 schema；仅支持 PostgreSQL（计划 §2 决策 3）
        migrations.RunSQL(
            'CREATE SCHEMA IF NOT EXISTS aoi_core;',
            reverse_sql='DROP SCHEMA IF EXISTS aoi_core CASCADE;',
        ),
        migrations.CreateModel(
            name='AuthzState',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('version', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': '"aoi_core"."authz_state"',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('module', models.CharField(max_length=32)),
                ('action', models.CharField(max_length=32)),
                ('name_cn', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': '"aoi_core"."permission"',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name_cn', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_builtin', models.BooleanField(default=True)),
            ],
            options={
                'db_table': '"aoi_core"."role"',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('pk', models.CompositePrimaryKey('role_id', 'permission_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('role_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': '"aoi_core"."role_permission"',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('pk', models.CompositePrimaryKey('user_id', 'role_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('role_id', models.IntegerField()),
                ('granted_by', models.IntegerField(blank=True, null=True)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': '"aoi_core"."user_role"',
            },
        ),
        # 授权版本号单行（id 固定 1）：判定侧每请求读它做缓存失效依据
        migrations.RunSQL(
            'INSERT INTO aoi_core.authz_state (id, version, updated_at) VALUES (1, 0, now()) '
            'ON CONFLICT (id) DO NOTHING;',
            reverse_sql='DELETE FROM aoi_core.authz_state WHERE id = 1;',
        ),
    ]
