"""环境变量契约。

对齐 docs/contracts/平台B_接口与数据契约.md、
    infer-platform/deploy/.env.example。

TODO: 用 pydantic 定义 Settings，读取以下环境变量：
  PORT / INSTANCE_CODE / LOG_LEVEL / DB_PATH / DATA_DIR /
  MODEL_REGISTRY / MODEL_REGISTRY_USER / MODEL_REGISTRY_TOKEN / MODEL_PULL_MODE /
  TRAIN_PLATFORM_BASE_URL / INTERNAL_TOKEN / ONNX_PROVIDER /
  INSPECT_CONCURRENCY / INSPECT_QUEUE_MAX / INFER_TIMEOUT_MS /
  AUTO_PASS_KEEP_IMAGE / AUTO_PASS_KEEP_THUMB / IMAGE_RETENTION_DAYS /
  MODEL_KEEP_VERSIONS / REPORT_RETENTION_DAYS / REPORT_CRON /
  OUTBOX_MAX_AGE_HOURS / PULL_TMP_TTL_HOURS
"""
